name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        go: ["1.22"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=1m
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
